Restoration of passages cut out in abridged version
standardebooks/rolf-boldrewood_robbery-under-arms pull request #3
Opened 2021-03-30 00:18 UTC by drgrigg

This a heck of a big pull request! Some 30,000 + words were added, and a lot of chapters renumbered. I see there are some conflicts, but I'll figure out how to resolve those.

2021-03-30 00:30 UTC, drgrigg commented
Alex: I think I've resolved the conflicts so it's ready to merge if you approve.

2021-03-30 16:10 UTC, acabal commented
It still says there are conflicts in the PR. Can you take a look?

2021-03-30 21:54 UTC, drgrigg commented
Maybe I’m not doing it right. I edited the conflicted files using Github’s online editor and saved them. Anyway, I’ll have another look. There were only three files flagged as having conflicts.
On 31 Mar 2021, 3:11 AM +1100, Alex Cabal ***@***.***>, wrote:
> It still says there are conflicts in the PR. Can you take a look?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-30 21:58 UTC, drgrigg commented
Alex: when I log on it’s telling me “This branch has no conflicts with the base branch”.

2021-03-30 22:32 UTC, acabal commented
That's not what it says for me, it says this branch cannot be rebased on due to conflicts. Try rebasing on to master from your local repo, then fixing any merge commits there, and then force pushing to the PR.

2021-03-30 23:21 UTC, drgrigg commented
Rebasing terrifies me, but I think I've done it all correctly. Still seeing the message "This branch has no conflicts with the base branch"

2021-03-31 20:27 UTC, acabal requested changes

2021-03-31 20:27 UTC, acabal commented on src/epub/text/endnotes.xhtml
> +					<p>This is the author’s preface to the abridged one-volume edition published in 1889. <cite>Editor</cite>. <a href="preface.xhtml#noteref-1" epub:type="backlink">↩</a></p>
Is "Editor" you? If so, let's use `S.E. Editor` to clarify, with an em dash.

2021-04-01 00:43 UTC, drgrigg commented
OK, fixed the endnote and added an se:role of ann to myself.

2021-04-01 00:44 UTC, merged

2021-04-01 00:44 UTC, acabal commented
Excellent, thanks!